version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    networks:
      - springboot-mysql-network
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network